export interface InvoiceTable {
  id_order: string;
  id_bill: string;
  id_customer: string;
  createdate: string;
  type_account: boolean;
  tax_code: number;
  name_company: string;
  content_bill: string;
  dvt: number;
  amount: number;
  price: number;
  into_money: number;
  vat: number;
  total_vat: number;
  address: string;
  presentative: string;
  position: string;
  phone_number: number;
  email: string;
  status: boolean;
}

const DataInvoiceTable: InvoiceTable[] = [
  {
    id_order: 'ORD001',
    id_bill: 'BILL001',
    id_customer: 'KH011',
    createdate: '2023-01-01',
    type_account: true,
    tax_code: 1234567890,
    name_company: 'RedTech',
    content_bill: 'Laptop Purchase',
    dvt: 2,
    amount: 5,
    price: 1500,
    into_money: 7500,
    vat: 10,
    total_vat: 8250,
    address: 'Hà Nội',
    presentative: 'Nguyễn Mạnh Cường',
    position: 'CEO',
    phone_number: 1234567890,
    email: 'invoice@redtech.com',
    status: true,
  },
  {
    id_customer: 'KH012',
    id_order: 'ORD002',
    id_bill: 'BILL002',
    createdate: '2023-02-15',
    type_account: false,
    tax_code: 9876543210,
    name_company: 'GreenTech',
    content_bill: 'Server Installation',
    dvt: 1,
    amount: 10,
    price: 2000,
    into_money: 20000,
    vat: 15,
    total_vat: 23000,
    address: 'Hồ Chí Minh',
    presentative: 'Nguyễn Mạnh Phi',
    position: 'Quản lý',
    phone_number: 2345678901,
    email: 'invoice@greentech.com',
    status: true,
  },
  {
    id_order: 'ORD003',
    id_customer: 'KH013',

    id_bill: 'BILL003',
    createdate: '2023-03-10',
    type_account: true,
    tax_code: 1928374650,
    name_company: 'BlueTech',
    content_bill: 'Software Development',
    dvt: 3,
    amount: 8,
    price: 3000,
    into_money: 24000,
    vat: 10,
    total_vat: 26400,
    address: 'Đà Nẵng',
    presentative: 'Nguyễn Mạnh Duyên',
    position: 'Kế toán',
    phone_number: 3456789012,
    email: 'invoice@bluetech.com',
    status: false,
  },
  {
    id_customer: 'KH0134',
    id_order: 'ORD004',
    id_bill: 'BILL004',
    createdate: '2023-04-05',
    type_account: false,
    tax_code: 5647382910,
    name_company: 'GreyTech',
    content_bill: 'Consulting Services',
    dvt: 2,
    amount: 15,
    price: 1000,
    into_money: 15000,
    vat: 5,
    total_vat: 15750,
    address: 'Bình Định',
    presentative: 'Nguyễn Mạnh Huệ',
    position: 'Tech Leader',
    phone_number: 4567890123,
    email: 'invoice@greytech.com',
    status: true,
  },
  {
    id_order: 'ORD005',
    id_customer: 'KH0003',

    id_bill: 'BILL005',
    createdate: '2023-05-20',
    type_account: true,
    tax_code: 1092837465,
    name_company: 'PinkTech',
    content_bill: 'Cloud Hosting',
    dvt: 1,
    amount: 20,
    price: 500,
    into_money: 10000,
    vat: 10,
    total_vat: 11000,
    address: 'Nha Trang',
    presentative: 'Nguyễn Mạnh Toản',
    position: 'CEO',
    phone_number: 5678901234,
    email: 'invoice@pinktech.com',
    status: false,
  },
  {
    id_order: 'ORD006',
    id_customer: 'KH0134',
    id_bill: 'BILL006',
    createdate: '2023-06-01',
    type_account: false,
    tax_code: 8765432109,
    name_company: 'WhiteTech',
    content_bill: 'Network Security',
    dvt: 3,
    amount: 25,
    price: 800,
    into_money: 20000,
    vat: 15,
    total_vat: 23000,
    address: 'Thái Bình',
    presentative: 'Nguyễn Mạnh Khải',
    position: 'Marketing Manager',
    phone_number: 6789012345,
    email: 'invoice@whitetech.com',
    status: true,
  },
  {
    id_order: 'ORD007',
    id_bill: 'BILL007',
    id_customer: 'KH0133',

    createdate: '2023-07-15',
    type_account: true,
    tax_code: 3456789012,
    name_company: 'BlackTech',
    content_bill: 'IT Infrastructure',
    dvt: 2,
    amount: 30,
    price: 1200,
    into_money: 36000,
    vat: 10,
    total_vat: 39600,
    address: 'Hà Nội',
    presentative: 'Nguyễn Mạnh Trường',
    position: 'Sales Manager',
    phone_number: 7890123456,
    email: 'invoice@blacktech.com',
    status: false,
  },
  {
    id_order: 'ORD008',
    id_bill: 'BILL008',
    id_customer: 'KH0345',

    createdate: '2023-08-10',
    type_account: false,
    tax_code: 1230984567,
    name_company: 'YellowTech',
    content_bill: 'AI Development',
    dvt: 1,
    amount: 12,
    price: 5000,
    into_money: 60000,
    vat: 10,
    total_vat: 66000,
    address: 'Hà Nội',
    presentative: 'Nguyễn Mạnh Hải',
    position: 'CEO',
    phone_number: 1234567012,
    email: 'invoice@yellowtech.com',
    status: true,
  },
  {
    id_order: 'ORD009',
    id_bill: 'BILL009',
    id_customer: 'KH090',

    createdate: '2023-09-05',
    type_account: true,
    tax_code: 8976543210,
    name_company: 'OrangeTech',
    content_bill: 'Data Science Project',
    dvt: 2,
    amount: 10,
    price: 4000,
    into_money: 40000,
    vat: 12,
    total_vat: 44800,
    address: 'Hồ Chí Minh',
    presentative: 'Nguyễn Mạnh Lâm',
    position: 'CTO',
    phone_number: 3456781234,
    email: 'invoice@orangetech.com',
    status: false,
  },
  {
    id_order: 'ORD010',
    id_bill: 'BILL010',
    id_customer: 'KH011',

    createdate: '2023-10-01',
    type_account: false,
    tax_code: 5463728190,
    name_company: 'PurpleTech',
    content_bill: 'Mobile App Development',
    dvt: 1,
    amount: 18,
    price: 4500,
    into_money: 81000,
    vat: 10,
    total_vat: 89100,
    address: 'Đà Nẵng',
    presentative: 'Nguyễn Mạnh Sơn',
    position: 'DevOps Engineer',
    phone_number: 4567895678,
    email: 'invoice@purpletech.com',
    status: true,
  },
];

export { DataInvoiceTable };
