import img1 from 'src/assets/images/profile/user-1.jpg';
import img2 from 'src/assets/images/profile/user-2.jpg';

export interface AffiliateTable {
  id_order: string;
  id_publisher: string;
  createdate: string;
  name_publisher: string;
  email_publisher: string;
  phonenumber_publisher: string;
  imgsrc: string;
  name_customer: string;
  email_customer: string;
  phonenumber_customer: string;
  package: string;
  numberpoint: number;
  value: number;
  commission: number;
  status: string;
}

export interface HistoryTable {
  id_checkout: string;
  date_request: string;
  imgsrc: string;
  name_publisher: string;
  email: string;
  phone_number: string;
  number_money: string;
  bank_name: string;
  bank_amount: number;
  own_bank: string;
  bank_number: number;
  branch: string;
  bill: string;
  notification: string;
  date_done: string;
  paid: boolean;
  checked: boolean;
  status: string;
}

export interface PublisherTable {}

const DataPublisherTable: PublisherTable[] = [];

const DataAffiliateTable: AffiliateTable[] = [
  {
    id_order: '1',
    id_publisher: 'PUB001',
    createdate: '2024-07-18',
    name_publisher: 'Lâm Đình Khoa',
    email_publisher: 'khoa.ld@redon.com',
    phonenumber_publisher: '0901234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Active',
  },
  {
    id_order: '2',
    id_publisher: 'PUB002',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Toản',
    email_publisher: 'toan.nd@redon.com',
    phonenumber_publisher: '0912345678',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Pending',
  },
  {
    id_order: '3',
    id_publisher: 'PUB003',
    createdate: '2024-07-18',
    name_publisher: 'Ngô Đình Hòa',
    email_publisher: 'hoa.nd@redon.com',
    phonenumber_publisher: '0931234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Active',
  },
  {
    id_order: '4',
    id_publisher: 'PUB004',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Trường',
    email_publisher: 'truong.nd@redon.com',
    phonenumber_publisher: '0941234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Pending',
  },
  {
    id_order: '5',
    id_publisher: 'PUB005',
    createdate: '2024-07-18',
    name_publisher: 'Ngô Đình Khải',
    email_publisher: 'khai.nd@redon.com',
    phonenumber_publisher: '0951234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Active',
  },
  {
    id_order: '6',
    id_publisher: 'PUB006',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Chung',
    email_publisher: 'chung.nd@redon.com',
    phonenumber_publisher: '0961234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Pending',
  },
  {
    id_order: '7',
    id_publisher: 'PUB007',
    createdate: '2024-07-18',
    name_publisher: 'Nguyễn Đăng Hòa',
    email_publisher: 'hoa.nd@redon.com',
    phonenumber_publisher: '0971234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Active',
  },
  {
    id_order: '8',
    id_publisher: 'PUB008',
    createdate: '2024-07-19',
    name_publisher: 'Nguyễn Đăng Khánh',
    email_publisher: 'khanh.nd@redon.com',
    phonenumber_publisher: '0981234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Pending',
  },
];

const DataHistoryTable: HistoryTable[] = [
  {
    id_checkout: 'CHK001',
    date_request: '2024-07-18',
    imgsrc: img1,
    name_publisher: 'Lâm Đình Khoa',
    email: 'khoa.ld@redon.com',
    phone_number: '0901234567',
    number_money: '500,000 VND',
    bank_name: 'Vietcombank',
    bank_amount: 500000,
    own_bank: 'Lâm Đình Khoa',
    bank_number: 123456789,
    branch: 'Hà Nội',
    bill: 'BL001',
    notification: 'Payment requested',
    date_done: '2024-07-20',
    paid: true,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK002',
    date_request: '2024-07-19',
    imgsrc: img1,
    name_publisher: 'Ngô Đình Toản',
    email: 'toan.nd@redon.com',
    phone_number: '0912345678',
    number_money: '1,000,000 VND',
    bank_name: 'Techcombank',
    bank_amount: 1000000,
    own_bank: 'Ngô Đình Toản',
    bank_number: 987654321,
    branch: 'TP HCM',
    bill: 'BL002',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Từ chối',
  },
  {
    id_checkout: 'CHK003',
    date_request: '2024-07-20',
    imgsrc: img1,
    name_publisher: 'Nguyễn Thùy Linh',
    email: 'linh.nt@redon.com',
    phone_number: '0965842361',
    number_money: '700,000 VND',
    bank_name: 'ACB',
    bank_amount: 700000,
    own_bank: 'Nguyễn Thùy Linh',
    bank_number: 112233445,
    branch: 'Đà Nẵng',
    bill: 'BL003',
    notification: 'Awaiting payment',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Từ chối',
  },
  {
    id_checkout: 'CHK004',
    date_request: '2024-07-21',
    imgsrc: img1,
    name_publisher: 'Ngô Đình Hòa',
    email: 'hoa.nd@redon.com',
    phone_number: '0931234567',
    number_money: '300,000 VND',
    bank_name: 'Vietinbank',
    bank_amount: 300000,
    own_bank: 'Ngô Đình Hòa',
    bank_number: 556677889,
    branch: 'Hải Phòng',
    bill: 'BL004',
    notification: 'Payment rejected',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK005',
    date_request: '2024-07-22',
    imgsrc: img1,
    name_publisher: 'Nguyễn Đăng Khánh',
    email: 'khanh.nd@redon.com',
    phone_number: '0981234567',
    number_money: '900,000 VND',
    bank_name: 'MB Bank',
    bank_amount: 900000,
    own_bank: 'Nguyễn Đăng Khánh',
    bank_number: 998877665,
    branch: 'Cần Thơ',
    bill: 'BL005',
    notification: 'Payment requested',
    date_done: '2024-07-24',
    paid: true,
    checked: true,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK006',
    date_request: '2024-07-23',
    imgsrc: img1,
    name_publisher: 'Nguyễn Văn A',
    email: 'van.a@redon.com',
    phone_number: '0923456789',
    number_money: '1,200,000 VND',
    bank_name: 'Sacombank',
    bank_amount: 1200000,
    own_bank: 'Nguyễn Văn A',
    bank_number: 776655443,
    branch: 'Đà Lạt',
    bill: 'BL006',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK007',
    date_request: '2024-07-24',
    imgsrc: img1,
    name_publisher: 'Trần Thị B',
    email: 'thi.b@redon.com',
    phone_number: '0939876543',
    number_money: '800,000 VND',
    bank_name: 'BIDV',
    bank_amount: 800000,
    own_bank: 'Trần Thị B',
    bank_number: 345678901,
    branch: 'Huế',
    bill: 'BL007',
    notification: 'Payment requested',
    date_done: '2024-07-26',
    paid: true,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK008',
    date_request: '2024-07-25',
    imgsrc: img1,
    name_publisher: 'Lê Quốc C',
    email: 'quoc.c@redon.com',
    phone_number: '0912349876',
    number_money: '2,000,000 VND',
    bank_name: 'Eximbank',
    bank_amount: 2000000,
    own_bank: 'Lê Quốc C',
    bank_number: 554433221,
    branch: 'Nha Trang',
    bill: 'BL008',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK009',
    date_request: '2024-07-26',
    imgsrc: img1,
    name_publisher: 'Phạm Thị D',
    email: 'thi.d@redon.com',
    phone_number: '0923567890',
    number_money: '1,500,000 VND',
    bank_name: 'Vietcombank',
    bank_amount: 1500000,
    own_bank: 'Phạm Thị D',
    bank_number: 123789654,
    branch: 'Quảng Ninh',
    bill: 'BL009',
    notification: 'Payment rejected',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK010',
    date_request: '2024-07-27',
    imgsrc: img1,
    name_publisher: 'Đỗ Văn E',
    email: 'van.e@redon.com',
    phone_number: '0912765432',
    number_money: '600,000 VND',
    bank_name: 'TPBank',
    bank_amount: 600000,
    own_bank: 'Đỗ Văn E',
    bank_number: 554433112,
    branch: 'Hà Nội',
    bill: 'BL010',
    notification: 'Awaiting payment',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Từ chối',
  },
];

export { DataAffiliateTable, DataHistoryTable, DataPublisherTable };
