import img1 from 'src/assets/images/profile/user-1.jpg';
import img2 from 'src/assets/images/profile/user-2.jpg';

export interface AffiliateTable {
  id_order: string;
  id_publisher: string;
  createdate: string;
  name_publisher: string;
  email_publisher: string;
  phonenumber_publisher: string;
  imgsrc: string;
  name_customer: string;
  email_customer: string;
  phonenumber_customer: string;
  package: string;
  numberpoint: number;
  value: number;
  commission: number;
  status: string;
}

export interface HistoryTable {
  id_checkout: string;
  date_request: string;
  imgsrc: string;
  name_publisher: string;
  email: string;
  phone_number: string;
  number_money: string;
  bank_name: string;
  bank_amount: number;
  own_bank: string;
  bank_number: number;
  branch: string;
  bill: string;
  notification: string;
  date_done: string;
  paid: boolean;
  checked: boolean;
  status: string;
}

export interface PublisherTable {
  id_publisher: string;
  imgsrc: string;
  name_partner: string;
  email: string;
  phone_number: number;
  type: boolean;
  create_date: string;
  type_account: number;
  rank: string;
  brief: boolean;
  contract: string;
  total_commission: number;
  click: number;
  customer: string;
  order: string;
  revenue: number;
  cvr: number;
  account_balance: number;
  processing: number;
  paid: number;
  total_Customers: number;
  total_Order: number;
}

export interface ContactAffiliateTable {
  id_contract: string;
  id_customer: string;
  icon: string;
  createdate: string;
  confirmdate: string;
  type_company: boolean;
  name_company: string;
  tax_code: number;
  address: string;
  representative: string;
  position: string;
  phone_number: number;
  email: string;
  status: number;
}

export interface ContactPointTable {
  id_contract: string;
  id_customer: string;
  icon: string;
  createdate: string;
  confirmdate: string;
  type_company: boolean;
  name_company: string;
  tax_code: number;
  address: string;
  representative: string;
  position: string;
  phone_number: number;
  email: string;
  status: number;
}

const DataContactPointTable: ContactPointTable[] = [
  {
    id_contract: 'CNT001',
    id_customer: 'CUS001',
    icon: 'https://example.com/icon1.png',
    createdate: '2023-01-10',
    confirmdate: '2023-01-12',
    type_company: true,
    name_company: 'RedTech',
    tax_code: 1234567890,
    address: 'Hà Nội',
    representative: 'Nguyễn Mạnh Cường',
    position: 'CEO',
    phone_number: 1234567890,
    email: 'contact@companya.com',
    status: 1,
  },
  {
    id_contract: 'CNT002',
    id_customer: 'CUS002',
    icon: 'https://example.com/icon2.png',
    createdate: '2023-02-05',
    confirmdate: '2023-02-07',
    type_company: false,
    name_company: 'GreenTech',
    tax_code: 9876543210,
    address: 'Hồ Chí Minh',
    representative: 'Nguyễn Mạnh Phi',
    position: 'Quản lý',
    phone_number: 2345678901,
    email: 'contact@companyb.com',
    status: 2,
  },
  {
    id_contract: 'CNT003',
    id_customer: 'CUS003',
    icon: 'https://example.com/icon3.png',
    createdate: '2023-03-12',
    confirmdate: '2023-03-15',
    type_company: true,
    name_company: 'BlueTech',
    tax_code: 1928374650,
    address: 'Đà Nẵng',
    representative: 'Nguyễn Mạnh Duyên',
    position: 'Kế toán',
    phone_number: 3456789012,
    email: 'contact@companyc.com',
    status: 3,
  },
  {
    id_contract: 'CNT004',
    id_customer: 'CUS004',
    icon: 'https://example.com/icon4.png',
    createdate: '2023-04-10',
    confirmdate: '2023-04-13',
    type_company: false,
    name_company: 'GreyTech',
    tax_code: 5647382910,
    address: 'Bình Định',
    representative: 'Nguyễn Mạnh Huệ',
    position: 'Tech leader',
    phone_number: 4567890123,
    email: 'contact@companyd.com',
    status: 4,
  },
  {
    id_contract: 'CNT005',
    id_customer: 'CUS005',
    icon: 'https://example.com/icon5.png',
    createdate: '2023-05-08',
    confirmdate: '2023-05-10',
    type_company: true,
    name_company: 'PinkTech',
    tax_code: 1092837465,
    address: 'Nha Trang',
    representative: 'Nguyễn Mạnh Toản',
    position: 'CEO',
    phone_number: 5678901234,
    email: 'contact@companye.com',
    status: 2,
  },
  {
    id_contract: 'CNT006',
    id_customer: 'CUS006',
    icon: 'https://example.com/icon6.png',
    createdate: '2023-06-15',
    confirmdate: '2023-06-18',
    type_company: false,
    name_company: 'WhiteTech',
    tax_code: 8765432109,
    address: 'Thái Bình',
    representative: 'Nguyễn Mạnh Khải',
    position: 'Trường phòng marketing',
    phone_number: 6789012345,
    email: 'contact@companyf.com',
    status: 1,
  },
  {
    id_contract: 'CNT007',
    id_customer: 'CUS007',
    icon: 'https://example.com/icon7.png',
    createdate: '2023-07-09',
    confirmdate: '2023-07-12',
    type_company: true,
    name_company: 'BlackTech',
    tax_code: 3456789012,
    address: 'Hà Nội',
    representative: 'Nguyễn Mạnh Trường',
    position: 'Trưởng phòng kinh doanh',
    phone_number: 7890123456,
    email: 'contact@companyg.com',
    status: 3,
  },
];

const DataContactAffiliateTable: ContactAffiliateTable[] = [
  {
    id_contract: 'CNT001',
    id_customer: 'CUS001',
    icon: 'https://example.com/icon1.png',
    createdate: '2023-01-10',
    confirmdate: '2023-01-12',
    type_company: true,
    name_company: 'RedTech',
    tax_code: 1234567890,
    address: 'Hà Nội',
    representative: 'Nguyễn Mạnh Cường',
    position: 'CEO',
    phone_number: 1234567890,
    email: 'contact@companya.com',
    status: 1,
  },
  {
    id_contract: 'CNT002',
    id_customer: 'CUS002',
    icon: 'https://example.com/icon2.png',
    createdate: '2023-02-05',
    confirmdate: '2023-02-07',
    type_company: false,
    name_company: 'GreenTech',
    tax_code: 9876543210,
    address: 'Hồ Chí Minh',
    representative: 'Nguyễn Mạnh Phi',
    position: 'Quản lý',
    phone_number: 2345678901,
    email: 'contact@companyb.com',
    status: 2,
  },
  {
    id_contract: 'CNT003',
    id_customer: 'CUS003',
    icon: 'https://example.com/icon3.png',
    createdate: '2023-03-12',
    confirmdate: '2023-03-15',
    type_company: true,
    name_company: 'BlueTech',
    tax_code: 1928374650,
    address: 'Đà Nẵng',
    representative: 'Nguyễn Mạnh Duyên',
    position: 'Kế toán',
    phone_number: 3456789012,
    email: 'contact@companyc.com',
    status: 3,
  },
  {
    id_contract: 'CNT004',
    id_customer: 'CUS004',
    icon: 'https://example.com/icon4.png',
    createdate: '2023-04-10',
    confirmdate: '2023-04-13',
    type_company: false,
    name_company: 'GreyTech',
    tax_code: 5647382910,
    address: 'Bình Định',
    representative: 'Nguyễn Mạnh Huệ',
    position: 'Tech leader',
    phone_number: 4567890123,
    email: 'contact@companyd.com',
    status: 4,
  },
  {
    id_contract: 'CNT005',
    id_customer: 'CUS005',
    icon: 'https://example.com/icon5.png',
    createdate: '2023-05-08',
    confirmdate: '2023-05-10',
    type_company: true,
    name_company: 'PinkTech',
    tax_code: 1092837465,
    address: 'Nha Trang',
    representative: 'Nguyễn Mạnh Toản',
    position: 'CEO',
    phone_number: 5678901234,
    email: 'contact@companye.com',
    status: 2,
  },
  {
    id_contract: 'CNT006',
    id_customer: 'CUS006',
    icon: 'https://example.com/icon6.png',
    createdate: '2023-06-15',
    confirmdate: '2023-06-18',
    type_company: false,
    name_company: 'WhiteTech',
    tax_code: 8765432109,
    address: 'Thái Bình',
    representative: 'Nguyễn Mạnh Khải',
    position: 'Trường phòng marketing',
    phone_number: 6789012345,
    email: 'contact@companyf.com',
    status: 3,
  },
  {
    id_contract: 'CNT007',
    id_customer: 'CUS007',
    icon: 'https://example.com/icon7.png',
    createdate: '2023-07-09',
    confirmdate: '2023-07-12',
    type_company: true,
    name_company: 'BlackTech',
    tax_code: 3456789012,
    address: 'Hà Nội',
    representative: 'Nguyễn Mạnh Trường',
    position: 'Trưởng phòng kinh doanh',
    phone_number: 7890123456,
    email: 'contact@companyg.com',
    status: 1,
  },
];

const DataPublishersTable: PublisherTable[] = [
  {
    id_publisher: 'PUB001',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Quân',
    email: 'partnerB@example.com',
    phone_number: 1234567890,
    type: true,
    create_date: '2023-01-15',
    type_account: 1,
    rank: 'Rank C',
    contract: 'Chờ duyệt', // Moved here
    brief: true, // Moved here
    total_commission: 10000,
    click: 5000,
    customer: 'Customer A',
    order: 'Order001',
    revenue: 10000000,
    cvr: 5.0,
    account_balance: 2000,
    processing: 500,
    paid: 1500,
    total_Customers: 50,
    total_Order: 150,
  },
  {
    id_publisher: 'PUB002',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Giám',
    email: 'partnerB@example.com',
    phone_number: 2345678901,
    type: false,
    create_date: '2023-02-10',
    type_account: 2,
    rank: 'Rank B',
    contract: 'Đã duyệt', // Moved here
    brief: true, // Moved here
    total_commission: 15000,
    click: 3000,
    customer: 'Customer B',
    order: 'Order002',
    revenue: 10000000,
    cvr: 6.5,
    account_balance: 3000,
    processing: 1000,
    paid: 2000,
    total_Customers: 10,
    total_Order: 100,
  },
  {
    id_publisher: 'PUB003',
    imgsrc: img2,
    name_partner: 'Hoàng Thành Thăng Long',
    email: 'partnerC@example.com',
    phone_number: 3456789012,
    type: true,
    create_date: '2023-03-05',
    type_account: 3,
    rank: 'Rank A',
    contract: 'Chờ duyệt', // Moved here
    brief: false, // Moved here
    total_commission: 7000,
    click: 4000,
    customer: 'Customer C',
    order: 'Order003',
    revenue: 10000000,
    cvr: 4.8,
    account_balance: 1200,
    processing: 600,
    paid: 800,
    total_Customers: 30,
    total_Order: 30,
  },
  {
    id_publisher: 'PUB004',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Trường',
    email: 'partnerD@example.com',
    phone_number: 4567890123,
    type: false,
    create_date: '2023-04-18',
    type_account: 1,
    rank: 'Rank A',
    contract: 'Từ chối', // Moved here
    brief: false, // Moved here
    total_commission: 20000,
    click: 7000,
    customer: 'Customer D',
    order: 'Order004',
    revenue: 10000000,
    cvr: 7.2,
    account_balance: 5000,
    processing: 1500,
    paid: 3500,
    total_Customers: 40,
    total_Order: 50,
  },
  {
    id_publisher: 'PUB005',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Toản',
    email: 'partnerE@example.com',
    phone_number: 5678901234,
    type: true,
    create_date: '2023-05-25',
    type_account: 2,
    rank: 'Rank C',
    contract: 'Từ chối', // Moved here
    brief: false, // Moved here
    total_commission: 11000,
    click: 4500,
    customer: 'Customer E',
    order: 'Order005',
    revenue: 10000000,
    cvr: 5.4,
    account_balance: 2500,
    processing: 800,
    paid: 1700,
    total_Customers: 60,
    total_Order: 150,
  },
  {
    id_publisher: 'PUB006',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Khải',
    email: 'partnerF@example.com',
    phone_number: 6789012345,
    type: false,
    create_date: '2023-06-08',
    type_account: 3,
    rank: 'Rank A',
    contract: 'Chưa gửi', // Moved here
    brief: false, // Moved here
    total_commission: 5000,
    click: 2500,
    customer: 'Customer F',
    order: 'Order006',
    revenue: 10000000,
    cvr: 3.9,
    account_balance: 800,
    processing: 300,
    paid: 500,
    total_Customers: 10,
    total_Order: 50,
  },
  {
    id_publisher: 'PUB007',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Đức',
    email: 'partnerG@example.com',
    phone_number: 7890123456,
    type: true,
    create_date: '2023-07-01',
    type_account: 3,
    rank: 'Rank D',
    contract: 'Từ chối', // Moved here
    brief: false, // Moved here
    total_commission: 9000,
    click: 3200,
    customer: 'Customer G',
    order: 'Order007',
    revenue: 10000000,
    cvr: 4.5,
    account_balance: 1700,
    processing: 500,
    paid: 1200,
    total_Customers: 20,
    total_Order: 40,
  },
  {
    id_publisher: 'PUB008',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Mẫn',
    email: 'partnerH@example.com',
    phone_number: 8901234567,
    type: false,
    create_date: '2023-08-15',
    type_account: 2,
    rank: 'Rank C',
    contract: 'Chưa gửi', // Moved here
    brief: false, // Moved here
    total_commission: 18000,
    click: 6000,
    customer: 'Customer H',
    order: 'Order008',
    revenue: 10000000,
    cvr: 6.0,
    account_balance: 4000,
    processing: 1200,
    paid: 2800,
    total_Customers: 30,
    total_Order: 40,
  },
  {
    id_publisher: 'PUB009',
    imgsrc: img2,
    name_partner: 'Hoàng Đại Minh Tinh',
    email: 'partnerI@example.com',
    phone_number: 9012345678,
    type: true,
    create_date: '2023-09-10',
    type_account: 2,
    rank: 'Rank B',
    contract: 'Chưa gửi', // Moved here
    brief: false, // Moved here
    total_commission: 6000,
    click: 3500,
    customer: 'Customer I',
    order: 'Order009',
    revenue: 10000000,
    cvr: 4.2,
    account_balance: 1000,
    processing: 400,
    paid: 600,
    total_Customers: 20,
    total_Order: 40,
  },
  {
    id_publisher: 'PUB010',
    imgsrc: img2,
    name_partner: 'Hoàng Minh Anh',
    email: 'partnerJ@example.com',
    phone_number: 1234567890,
    type: false,
    create_date: '2023-10-05',
    type_account: 3,
    rank: 'Rank A',
    contract: 'Đã duyệt', // Moved here
    brief: true, // Moved here
    total_commission: 14000,
    click: 5500,
    customer: 'Customer J',
    order: 'Order010',
    revenue: 10000000,
    cvr: 5.8,
    account_balance: 3500,
    processing: 1000,
    paid: 2500,
    total_Customers: 50,
    total_Order: 150,
  },
];

const DataAffiliateTable: AffiliateTable[] = [
  {
    id_order: '1',
    id_publisher: 'PUB001',
    createdate: '2024-07-18',
    name_publisher: 'Lâm Đình Khoa',
    email_publisher: 'khoa.ld@redon.com',
    phonenumber_publisher: '0901234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Hoạt động',
  },
  {
    id_order: '2',
    id_publisher: 'PUB002',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Toản',
    email_publisher: 'toan.nd@redon.com',
    phonenumber_publisher: '0912345678',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Hoạt động',
  },
  {
    id_order: '3',
    id_publisher: 'PUB003',
    createdate: '2024-07-18',
    name_publisher: 'Ngô Đình Hòa',
    email_publisher: 'hoa.nd@redon.com',
    phonenumber_publisher: '0931234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Chờ duyệt',
  },
  {
    id_order: '4',
    id_publisher: 'PUB004',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Trường',
    email_publisher: 'truong.nd@redon.com',
    phonenumber_publisher: '0941234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Từ chối',
  },
  {
    id_order: '5',
    id_publisher: 'PUB005',
    createdate: '2024-07-18',
    name_publisher: 'Ngô Đình Khải',
    email_publisher: 'khai.nd@redon.com',
    phonenumber_publisher: '0951234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Chưa đăng ký',
  },
  {
    id_order: '6',
    id_publisher: 'PUB006',
    createdate: '2024-07-19',
    name_publisher: 'Ngô Đình Chung',
    email_publisher: 'chung.nd@redon.com',
    phonenumber_publisher: '0961234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Chưa đăng ký',
  },
  {
    id_order: '7',
    id_publisher: 'PUB007',
    createdate: '2024-07-18',
    name_publisher: 'Nguyễn Đăng Hòa',
    email_publisher: 'hoa.nd@redon.com',
    phonenumber_publisher: '0971234567',
    imgsrc: img1,
    name_customer: 'Lê Tài Đức',
    email_customer: 'duc.lt@redon.com',
    phonenumber_customer: '0987654321',
    package: 'Gói A',
    numberpoint: 70,
    value: 70000,
    commission: 5000,
    status: 'Từ chối',
  },
  {
    id_order: '8',
    id_publisher: 'PUB008',
    createdate: '2024-07-19',
    name_publisher: 'Nguyễn Đăng Khánh',
    email_publisher: 'khanh.nd@redon.com',
    phonenumber_publisher: '0981234567',
    imgsrc: img2,
    name_customer: 'Nguyễn Thùy Linh',
    email_customer: 'linh.nt@redon.com',
    phonenumber_customer: '0965842361',
    package: 'Gói B',
    numberpoint: 150,
    value: 150000,
    commission: 10000,
    status: 'Hoạt động',
  },
];

const DataHistoryTable: HistoryTable[] = [
  {
    id_checkout: 'CHK001',
    date_request: '2024-07-18',
    imgsrc: img1,
    name_publisher: 'Lâm Đình Khoa',
    email: 'khoa.ld@redon.com',
    phone_number: '0901234567',
    number_money: '500,000 VND',
    bank_name: 'Vietcombank',
    bank_amount: 500000,
    own_bank: 'Lâm Đình Khoa',
    bank_number: 123456789,
    branch: 'Hà Nội',
    bill: 'BL001',
    notification: 'Payment requested',
    date_done: '2024-07-20',
    paid: true,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK002',
    date_request: '2024-07-19',
    imgsrc: img1,
    name_publisher: 'Ngô Đình Toản',
    email: 'toan.nd@redon.com',
    phone_number: '0912345678',
    number_money: '1,000,000 VND',
    bank_name: 'Techcombank',
    bank_amount: 1000000,
    own_bank: 'Ngô Đình Toản',
    bank_number: 987654321,
    branch: 'TP HCM',
    bill: 'BL002',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Từ chối',
  },
  {
    id_checkout: 'CHK003',
    date_request: '2024-07-20',
    imgsrc: img1,
    name_publisher: 'Nguyễn Thùy Linh',
    email: 'linh.nt@redon.com',
    phone_number: '0965842361',
    number_money: '700,000 VND',
    bank_name: 'ACB',
    bank_amount: 700000,
    own_bank: 'Nguyễn Thùy Linh',
    bank_number: 112233445,
    branch: 'Đà Nẵng',
    bill: 'BL003',
    notification: 'Awaiting payment',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Từ chối',
  },
  {
    id_checkout: 'CHK004',
    date_request: '2024-07-21',
    imgsrc: img1,
    name_publisher: 'Ngô Đình Hòa',
    email: 'hoa.nd@redon.com',
    phone_number: '0931234567',
    number_money: '300,000 VND',
    bank_name: 'Vietinbank',
    bank_amount: 300000,
    own_bank: 'Ngô Đình Hòa',
    bank_number: 556677889,
    branch: 'Hải Phòng',
    bill: 'BL004',
    notification: 'Payment rejected',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK005',
    date_request: '2024-07-22',
    imgsrc: img1,
    name_publisher: 'Nguyễn Đăng Khánh',
    email: 'khanh.nd@redon.com',
    phone_number: '0981234567',
    number_money: '900,000 VND',
    bank_name: 'MB Bank',
    bank_amount: 900000,
    own_bank: 'Nguyễn Đăng Khánh',
    bank_number: 998877665,
    branch: 'Cần Thơ',
    bill: 'BL005',
    notification: 'Payment requested',
    date_done: '2024-07-24',
    paid: true,
    checked: true,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK006',
    date_request: '2024-07-23',
    imgsrc: img1,
    name_publisher: 'Nguyễn Văn A',
    email: 'van.a@redon.com',
    phone_number: '0923456789',
    number_money: '1,200,000 VND',
    bank_name: 'Sacombank',
    bank_amount: 1200000,
    own_bank: 'Nguyễn Văn A',
    bank_number: 776655443,
    branch: 'Đà Lạt',
    bill: 'BL006',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK007',
    date_request: '2024-07-24',
    imgsrc: img1,
    name_publisher: 'Trần Thị B',
    email: 'thi.b@redon.com',
    phone_number: '0939876543',
    number_money: '800,000 VND',
    bank_name: 'BIDV',
    bank_amount: 800000,
    own_bank: 'Trần Thị B',
    bank_number: 345678901,
    branch: 'Huế',
    bill: 'BL007',
    notification: 'Payment requested',
    date_done: '2024-07-26',
    paid: true,
    checked: true,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK008',
    date_request: '2024-07-25',
    imgsrc: img1,
    name_publisher: 'Lê Quốc C',
    email: 'quoc.c@redon.com',
    phone_number: '0912349876',
    number_money: '2,000,000 VND',
    bank_name: 'Eximbank',
    bank_amount: 2000000,
    own_bank: 'Lê Quốc C',
    bank_number: 554433221,
    branch: 'Nha Trang',
    bill: 'BL008',
    notification: 'Payment in process',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Đã đi tiền',
  },
  {
    id_checkout: 'CHK009',
    date_request: '2024-07-26',
    imgsrc: img1,
    name_publisher: 'Phạm Thị D',
    email: 'thi.d@redon.com',
    phone_number: '0923567890',
    number_money: '1,500,000 VND',
    bank_name: 'Vietcombank',
    bank_amount: 1500000,
    own_bank: 'Phạm Thị D',
    bank_number: 123789654,
    branch: 'Quảng Ninh',
    bill: 'BL009',
    notification: 'Payment rejected',
    date_done: '2024-07-20',
    paid: false,
    checked: false,
    status: 'Chờ duyệt',
  },
  {
    id_checkout: 'CHK010',
    date_request: '2024-07-27',
    imgsrc: img1,
    name_publisher: 'Đỗ Văn E',
    email: 'van.e@redon.com',
    phone_number: '0912765432',
    number_money: '600,000 VND',
    bank_name: 'TPBank',
    bank_amount: 600000,
    own_bank: 'Đỗ Văn E',
    bank_number: 554433112,
    branch: 'Hà Nội',
    bill: 'BL010',
    notification: 'Awaiting payment',
    date_done: '2024-07-20',
    paid: false,
    checked: true,
    status: 'Từ chối',
  },
];

export {
  DataAffiliateTable,
  DataHistoryTable,
  DataPublishersTable,
  DataContactPointTable,
  DataContactAffiliateTable,
};
